wikipedia-dark.css
Updated https://github.com/StylishThemes/Wikipedia-Dark/pull/2
=> Add TOC colors

wikipedia-dark.css
-Use dark text color against light background
=> Improve table cell text visibility

wikipedia-dark.css
@Mottie wanted to run this by you first to see if you agree with this change and these selectors.
[Link](https://en.wikipedia.org/wiki/Ted_Cruz#Electoral_history)
=> Dark background and brighter text for table footer

wikipedia-dark.css
Added the [Related pages](https://en.wikipedia.org/wiki/Special:Preferences#mw-prefsection-betafeatures) that show up on the bottom of the page to the appropriate background sections
=> added Related pages from beta

wikipedia-dark.user.css
* Fix blue/cancel buttons that were showing up as generic ones
* Fix border colours on blue buttons
* Fix hover, active, focus and active+focus styles
**Screenshots...**
**Main page search...**
**Before + After:**
**Reference tooltips settings...**
**Before:**
**After:**
**Page preview settings...**
**Before:**
**After:**
**Edit page...**
**Normal...**
**Before:**
**After:**
**``:hover``**
**Before:**
**After:**
**``:active``**
**Before:**
**After:**
**``:focus``**
**Before:**
**After:**
**``:active:focus``**
**Before:**
**After:**
=> Improve button styles

wikipedia-dark.user.css
**Screenshots...**
**Settings...**
**Default:**
**Before:**
**After:**
**Disable notice...**
**Default:**
**Before:**
**After:**
=> Support page preview settings

wikipedia-dark.user.css
infobox not themed properly on polish version in Wikipedia, unecessary changing img color when focused, added color to "Not logged in"
=> Minor fixes

wikipedia-dark.user.css
=> Properly style positive value in Recent Changes page

wikipedia-dark.user.css
- Fixed notification UI "mark as read/unread" button colors
- Fixed background and padding of "More" menu elements
- Reduced brightness of the footer icon images
- Fixes background colors on the popups gadget
- Uses a regex for the domain selector instead of a domain list
=> Minor style tweaks

wikipedia-dark.user.css
<s>First whack at</s> Fixes #72
I'm attempting to reuse the existing color palette as much as possible, though at the moment some of the elements won't exactly match their desktop counterparts. I can hunt those down and fix them later.
<s>And yes, @the-j0k3r, I'll be merging all the selectors with duplicate declarations later (I can already hear you saying that). I'm still playing unstyled element whack-a-mole for now.</s> :smiley:
After thorough testing, the new mobile style (for Minerva) should now be complete:tm:.
=> Begin dark theme skeleton for mobile style

wikipedia-dark.user.css
This is causing a syntax error
=> Fix missing - in var

wikipedia-dark.user.css
- fixed dark color of blockquotes text
- fixed dark "X" icon for language change box
- fixed medical box information (polish version)
=> Few updates

wikipedia-dark.user.css
P.S. Happy anniversary, Wikipedia!
=> Fix 20-year birthday banner

wikipedia-dark.user.css
https://ru.wikipedia.org/wiki/Print_Screen
=> Fix keyboard keys

wikipedia-dark.user.css
=> Fix White Popup Background

wikipedia-dark.user.css
https://ru.m.wikipedia.org/wiki/Print_Screen
=> Fix keyboard keys again

wikipedia-dark.user.css
https://commons.wikimedia.org/wiki/Category:S.T.A.L.K.E.R.:_Shadow_of_Chernobyl
=> Fix projects background color

wikipedia-dark.user.css
Sometimes there are goes survey: "Does this page load fast enough?" "Yes/Not sure/No". For more information, see this survey's [privacy statement](https://foundation.wikimedia.org/wiki/Performance_Perception_Survey_Privacy_Statement).
=> Fix survey background color

wikipedia-dark.user.css
Tweaks swatch colours so that they appear as original regardless of the intrusive rule in place.
Also, a few of the cleanliness rules have been taken into account and have done the appropriate fixes.
=> Minor adjustments

wikipedia-dark.user.css
removed redundancies
corrected a faulty rule param
corrected group orientations [incomplete]
=> Small tweaks

wikipedia-dark.user.css
https://en.wikipedia.org/wiki/Queen_(band)
=> Fix table of contents gradient

wikipedia-dark.user.css
=> removed side container bottom gradient + other
