- wikipedia-dark.css
[Example](https://en.wikipedia.org/wiki/Kobo_eReader#Market_share)
> Use dark background for table header

- wikipedia-dark.css
[Example](https://en.wikipedia.org/wiki/EarthBound)
The default CSS uses alternating colors between the even and odd rows so I did the same thing here.
> Add dark background to even rows of infobox

- wikipedia-dark.css
to the background-color: #222; list
> Added .mwe-popups, .mwe-popups-is-not-tall, .mwe-popups-is-tall

- wikipedia-dark.css
Musical Tracks had a white background and light grey text, which made it difficult to read. The .tracklist panel extended too far to the right, so I made it transparent. I then made the header for the track list a grey color (#333333), and the background for the tracks a darker grey (#222222) with a light grey border (#555555). It fits the design pattern, formatted correctly, and does not cause any issues with other portions of the site (as far as I am aware).
> Darkened The Background For Musical Tracks

- wikipedia-dark.css
I was trying to find this one 
But cant grab with inspect and css from style editor was nothing I could see useful.
So ended up fixing the others :( that I could find, sadly had to add as is else theres arrows flying outside the box, anyway Ive lost my plot with these tooltips. Argh!
> fix tooltip/reversed

- wikipedia-dark.user.css
When using this dark theme with the wiki of RPCS3 (PS3 emulator) [https://wiki.rpcs3.net/] the infobox escapes the theme due to absence of this #f0f0f0 variant. Hope this is okay.
Here's a [link](https://wiki.rpcs3.net/index.php?title=God_of_War:_Collection) to see this happening.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Do let me know if anything else is required!
> Updating variant of #F0F0F0

- wikipedia-dark.user.css
I was trying to add dark theme for the scrollbar when I noticed your GitHub dark theme already has a neat version of it. So I've decided to use that instead and only removed GitHub specific portions. As with that theme, this addition only works on Chrome.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Do let me know if anything else is required!
> Extending the dark theme to cover the scrollbar

- wikipedia-dark.user.css
Ran into 2 cases of plainlinks not being displayed correctly:
1. The [version page](https://en.wikipedia.org/wiki/Special:Version) tables display fully with the header background colour. I've found that removing 'table.plainlinks' solves this. This line was added as part of the [initial commit](https://github.com/StylishThemes/Wikipedia-Dark/commit/33f62f3f81b5aa2ae1428cc3cd18c4ef2efd2fbd) itself so I'm not sure what it was meant to address. Hopefully doesn't break anything.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<br />
2. While using plainlinks in the [infobox of RPCS3 wiki](https://wiki.rpcs3.net/index.php?title=Catherine), I noticed links display pure white instead of blue. Removing '*' from 'span.plainlinks' address this problem. …
> Fix plainlinks table and infobox links

- wikipedia-dark.user.css
Message notifications that show up as a banner in the wiki page does not have a background making it pretty easy to miss. Added a background to let it stand out.
Original white theme
Before
After
Let me know if you have any comments!
> Add background color for user message pop-ups

- README.md
- wikipedia-dark.user.css
Hi, I made a couple changes.
1. Firstly, the infobox headers for extension weren't being captured by the theme. Here's an [example](https://www.mediawiki.org/wiki/Extension:Cargo) of it at work.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<br />
2. The current green seemed a tad too dark to me. I feel it doesn't show the positive nature of the extension being stable. So I opted to make it a mildly lighter shade that stays true to the theme and gives the look I was expecting. However, I understand that this boils down to tastes, so if you don't like it, I'll drop this commit.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<br />
3. Added wikimedia.org to the README since it is also supported now. …
> Added extension infobox + misc.

- README.md
- wikipedia-dark.user.css
Since a [dedicated scrollbar theme](https://github.com/StylishThemes/Overlay-Scrollbars) has been made, there is no longer a need to have it as part of this theme. 
The new style allows users to customise the scrollbar from the extension itself and works on Firefox as well. So I think it is a better solution to point users to it rather than baking it into this theme.
> Remove dedicated scrollbar code and add Overlay-Scrollbars to README

- wikipedia-dark.user.css
**Screenshots...**
**Before:**
**After:**
> Fix reference tooltip colours

- wikipedia-dark.user.css
StylishThemes/Wikipedia-Dark#30's changes were designed specifically with wikipedia.org in mind. When this repo's domains were later expanded to cover more than just wikipedia.org, the other domains' navigation menu logos got messed up.
This commit adds an extra @document rule specifically for wikipedia.org and moves the nav menu logo adjustments to it. Didn't move the main index page overrides there since they weren't breaking anything on the other domains.
**Wiktionary screenshots:**
**Before:**
**After:**
> Make nav menu logo adjustments Wikipedia-specific

- wikipedia-dark.user.css
Causes bullets and "m" ("This is a minor edit" indicator) on selected list items to appear as light grey instead of dark grey.
**Comparison screenshots ([Sega: Revision history](https://en.wikipedia.org/w/index.php?title=Sega&action=history)):**
**Before:**
**After:**
> Fix selected item colour in revision history

- wikipedia-dark.user.css
I've found that many articles in Russian (I didn't see this in English ones) don't apply dark style to their quotes. For example: Martin Niemöller's article (https://ru.wikipedia.org/wiki/Нимёллер,_Мартин)
Before:
After:
> Fix quotes in Russian articles

- wikipedia-dark.user.css
Adds all the other Wikimedia projects that were missing, plus explicitly specify the *.wikimedia.org wikis without accidentally applying to non-wiki sites (e.g. ticket.wikimedia.org).
> Better list of wikimedia sites

- wikipedia-dark.user.css
> Color the image titles properly

- wikipedia-dark.user.css
RPCS3 wiki now uses timeless theme by default, so having this theme enabled by default causes problems with the theme. If any user wishes to switch back to Vector, they can manually add this section back.
> Remove link for rpcs3.net

- wikipedia-dark.user.css
Fixed light gray text on light background in various weather tables. 
Example 1:
Before: ![](https://i.imgur.com/TkMnbG3.png)
After: ![](https://i.imgur.com/hfhBTfr.png)
Example 2:
Before: ![](https://i.imgur.com/LAYHSdn.png)
After: ![](https://i.imgur.com/4UFpGew.png)
Fixed issue with dark color and dark background on Russian version of Wikipedia
Before: ![](https://i.imgur.com/NlDqujY.png)
After: ![](https://i.imgur.com/GbWJcX4.png)
I hope this it will be enough. The color of these tables should be more unified...
> Fixes with weather tables

- wikipedia-dark.user.css
This is to fix several more issues with white background. All examples are taken from the page https://en.wikipedia.org/wiki/Riemann_hypothesis
- Commit https://github.com/StylishThemes/Wikipedia-Dark/commit/8304d001544a6600daa7e589ac7f038b5842b12e fixes white background for tables on desktop
- Commit https://github.com/StylishThemes/Wikipedia-Dark/commit/335aebb4d50056455c16b6be763ef65e185140c8 fixes white background on mobile quotebox
- Commit https://github.com/StylishThemes/Wikipedia-Dark/commit/958f8117fdafded492ed7540b6e5a71419f16006 fixes white background on mobile lazy loading placeholder image
- Commit https://github.com/StylishThemes/Wikipedia-Dark/commit/e04f567f362d6a8e7f551e516b47acee2d4b9587 is to remove redundant style (has been mentioned on line 2870 of the code). In …
> Miscellaneous white background fixes

- wikipedia-dark.user.css
I found a problem with some tables on the wiktionary: the text is too light and unreadable. For instance on [this page](https://en.wiktionary.org/wiki/limpiar):
With this PR it looks like so: 
Maybe a better solution would be to darken the background, but I don't know how to do that (the background is defined in a `style` attribute)
> Fix contrast issue with conjugation tables in wiktionary

- wikipedia-dark.user.css
Fix some backgrounds on the wiktionary:
* the sidebar is white in the French wiktionary, also, the "see also" banner is too light
* In the german wiktionary, see eg [this page](https://de.wiktionary.org/wiki/Ungarisch), where some headers are whitish, and the translation table too (there are many shades of white in this table alone...)
Screens:
> Fix Wiktionary backgrounds

- wikipedia-dark.user.css
Hello,
As I promised on previous PR - another bunch of various fixes. There are many improvements to article translation tool, search boxes, infoboxes, borders, tables, titles, polish or german subpages (needed to remove few because I saw @AfroThundr3007730 added similarr rules for them too) and more I forgot now where.
It fixes all issues for #167 and almost all #170 (even with charts colors, images can't be fixed).
Yes, I know about `!imporant` you don't like. Many elements couldn't be couldn't be overwritten because of being overwritten by more general rules of Dark Wikipedia style or by default Style. Or needed a lot longer rules to match these fixes.
Few examples of fixes below:
Have a nice day.
> Various fixes

- wikipedia-dark.user.css
Hello,
Another bunch of fixes for following sites:
1. https://en.wikipedia.org/wiki/Polka
2. https://en.wikipedia.org/wiki/Th%C3%B3rsm%C3%B6rk
3. https://en.wikipedia.org/wiki/Hematopoietic_stem_cell_transplantation
4. https://de.wikipedia.org/wiki/Wikipedia:Sprachen#Chronologie
5. https://pl.wikipedia.org/wiki/HD_188753_A_b
6. https://en.wikipedia.org/wiki/Wikipedia:Administrator_intervention_against_vandalism
7. https://en.wikipedia.org/wiki/Wikipedia:Content_translation_tool
8. https://en.wikipedia.org/wiki/12_Angry_Men_(1997_film)
9. https://pl.wikipedia.org/wiki/Alfa_Centauri
10. https://en.wikipedia.org/wiki/Trichotillomania
11. https://en.wikipedia.org/wiki/Dysosmia
12. https://en.wikipedia.org/wiki/General_Hux
13. https://en.wikipedia.org/wiki/Kong%C5%8D_Range#References
14. …
> Another bunch of fixes

- wikipedia-dark.user.css
my first pull req
(somewhat) fixes #200 
targets:
- text logo
- main sidebar
- article toc + sidebar
- search bar
- search bar results
also made a few other icons brighter
open for suggestions as usual
preview: 
(sorry for the personal configured text colors)
> new surface ui changes for english pages

- wikipedia-dark.user.css
targets:
- floating header (https://github.com/StylishThemes/Wikipedia-Dark/issues/200#issuecomment-1426859515)
- sidebar
- language selection panel buttons
- user menu icons
preview:
> new ui further updates

- wikipedia-dark.user.css
Fixed some buttons colors and backgrounds, dark text on dark backgrounds, some infoboxes and tables in EN/PL version. Includes and extends fixes related with white backgrounds and gradients in #217.
> Fixes to backgrounds, infoboxes and font colors
